sudo: required
services:
  - docker

before_install:
  - docker build -t myimage -f Dockerfile.dev .


script:
  - docker run -e CI=true myimage npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: docker-react
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-080149922798"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY    
   
